print("");print("ackley");
cat("bb: ");
cat(mean(ALLSLOPE1S["ackley", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["ackley", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["ackley", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["ackley", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["ackley", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["ackley", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["ackley", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["ackley", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["ackley", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["ackley", "vngc",]));
print("");
print("");print("alpine");
cat("bb: ");
cat(mean(ALLSLOPE1S["alpine", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["alpine", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["alpine", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["alpine", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["alpine", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["alpine", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["alpine", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["alpine", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["alpine", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["alpine", "vngc",]));
print("");
print("");print("eggholder");
cat("bb: ");
cat(mean(ALLSLOPE1S["eggholder", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["eggholder", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["eggholder", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["eggholder", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["eggholder", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["eggholder", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["eggholder", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["eggholder", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["eggholder", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["eggholder", "vngc",]));
print("");
print("");print("elliptic");
cat("bb: ");
cat(mean(ALLSLOPE1S["elliptic", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["elliptic", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["elliptic", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["elliptic", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["elliptic", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["elliptic", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["elliptic", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["elliptic", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["elliptic", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["elliptic", "vngc",]));
print("");
print("");print("goldsteinprice");
cat("bb: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["goldsteinprice", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["goldsteinprice", "vngc",]));
print("");
print("");print("griewank");
cat("bb: ");
cat(mean(ALLSLOPE1S["griewank", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["griewank", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["griewank", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["griewank", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["griewank", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["griewank", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["griewank", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["griewank", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["griewank", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["griewank", "vngc",]));
print("");
print("");print("levy");
cat("bb: ");
cat(mean(ALLSLOPE1S["levy", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["levy", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["levy", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["levy", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["levy", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["levy", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["levy", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["levy", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["levy", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["levy", "vngc",]));
print("");
print("");print("michalewicz");
cat("bb: ");
cat(mean(ALLSLOPE1S["michalewicz", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["michalewicz", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["michalewicz", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["michalewicz", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["michalewicz", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["michalewicz", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["michalewicz", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["michalewicz", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["michalewicz", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["michalewicz", "vngc",]));
print("");
print("");print("quadric");
cat("bb: ");
cat(mean(ALLSLOPE1S["quadric", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["quadric", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["quadric", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["quadric", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["quadric", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["quadric", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["quadric", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["quadric", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["quadric", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quadric", "vngc",]));
print("");
print("");print("quartic");
cat("bb: ");
cat(mean(ALLSLOPE1S["quartic", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["quartic", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["quartic", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["quartic", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["quartic", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["quartic", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["quartic", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["quartic", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["quartic", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["quartic", "vngc",]));
print("");
print("");print("rastrigin");
cat("bb: ");
cat(mean(ALLSLOPE1S["rastrigin", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["rastrigin", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["rastrigin", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["rastrigin", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["rastrigin", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["rastrigin", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["rastrigin", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["rastrigin", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["rastrigin", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rastrigin", "vngc",]));
print("");
print("");print("rosenbrock");
cat("bb: ");
cat(mean(ALLSLOPE1S["rosenbrock", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["rosenbrock", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["rosenbrock", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["rosenbrock", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["rosenbrock", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["rosenbrock", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["rosenbrock", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["rosenbrock", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["rosenbrock", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["rosenbrock", "vngc",]));
print("");
print("");print("salomon");
cat("bb: ");
cat(mean(ALLSLOPE1S["salomon", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["salomon", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["salomon", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["salomon", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["salomon", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["salomon", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["salomon", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["salomon", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["salomon", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["salomon", "vngc",]));
print("");
print("");print("schwefel1_2");
cat("bb: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["schwefel1_2", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel1_2", "vngc",]));
print("");
print("");print("schwefel2_22");
cat("bb: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["schwefel2_22", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_22", "vngc",]));
print("");
print("");print("schwefel2_26");
cat("bb: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["schwefel2_26", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["schwefel2_26", "vngc",]));
print("");
print("");print("sixhump");
cat("bb: ");
cat(mean(ALLSLOPE1S["sixhump", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["sixhump", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["sixhump", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["sixhump", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["sixhump", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["sixhump", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["sixhump", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["sixhump", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["sixhump", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["sixhump", "vngc",]));
print("");
print("");print("spherical");
cat("bb: ");
cat(mean(ALLSLOPE1S["spherical", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["spherical", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["spherical", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["spherical", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["spherical", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["spherical", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["spherical", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["spherical", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["spherical", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["spherical", "vngc",]));
print("");
print("");print("step");
cat("bb: ");
cat(mean(ALLSLOPE1S["step", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["step", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["step", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["step", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["step", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["step", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["step", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["step", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["step", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["step", "vngc",]));
print("");
print("");print("zakharov");
cat("bb: ");
cat(mean(ALLSLOPE1S["zakharov", "bb",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "bb",]));
print("");
cat("bba: ");
cat(mean(ALLSLOPE1S["zakharov", "bba",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "bba",]));
print("");
cat("gbest: ");
cat(mean(ALLSLOPE1S["zakharov", "gbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "gbest",]));
print("");
cat("gbestgc: ");
cat(mean(ALLSLOPE1S["zakharov", "gbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "gbestgc",]));
print("");
cat("lbest: ");
cat(mean(ALLSLOPE1S["zakharov", "lbest",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "lbest",]));
print("");
cat("lbestgc: ");
cat(mean(ALLSLOPE1S["zakharov", "lbestgc",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "lbestgc",]));
print("");
cat("spso: ");
cat(mean(ALLSLOPE1S["zakharov", "spso",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "spso",]));
print("");
cat("vn: ");
cat(mean(ALLSLOPE1S["zakharov", "vn",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "vn",]));
print("");
cat("vngc: ");
cat(mean(ALLSLOPE1S["zakharov", "vngc",]));
cat("   ");
cat(mean(ALLSLOPE2S["zakharov", "vngc",]));
print("");
